services:

  db:
    image: postgres:17
    container_name: find-my-ride-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1658
      POSTGRES_DB: find_my_ride

    ports:
      - "5434:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d find_my_ride"]
      interval: 10s
      timeout: 5s
      retries: 5


  api:
    build: .
    container_name: find-my-ride-api

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://postgres:1658@db:5432/find_my_ride

    depends_on:
      db:
        condition: service_healthy


volumes:
  postgres_data: